name: dbt-prod-deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install dbt-snowflake
      - run: dbt deps
      - run: dbt build --target prod --selector daily_dims
        env:
          DBT_ACCOUNT: ${{ secrets.DBT_ACCOUNT }}
          DBT_PROD_PASSWORD: ${{ secrets.DBT_PROD_PASSWORD }}