#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

source "$SCRIPT_DIR/../../../lib/common.sh"
source "$SCRIPT_DIR/../../../lib/fs.sh"
source "$SCRIPT_DIR/../../../lib/section.sh"

SCRIPT_NAME="11-airflow-init"

REPO_ROOT="$(get_repo_root "$SCRIPT_DIR")"
MODULE="$(get_module_root "$REPO_ROOT" "11-airflow")"

log "Creating 11-airflow structure..."

ensure_dir "$MODULE"

ensure_dir "$MODULE/learning-materials"
ensure_dir "$MODULE/learning-materials/02_airflow_installation_and_deployment"
ensure_dir "$MODULE/learning-materials/02_airflow_installation_and_deployment/dags"
ensure_dir "$MODULE/learning-materials/12_airflow_dbt_spark_lakehouse_architecture"
ensure_dir "$MODULE/learning-materials/12_airflow_dbt_spark_lakehouse_architecture/airflow_lakehouse_repo_template"
ensure_dir "$MODULE/learning-materials/12_airflow_dbt_spark_lakehouse_architecture/airflow_lakehouse_repo_template/config"
ensure_dir "$MODULE/learning-materials/12_airflow_dbt_spark_lakehouse_architecture/airflow_lakehouse_repo_template/dags"
ensure_dir "$MODULE/learning-materials/12_airflow_dbt_spark_lakehouse_architecture/airflow_lakehouse_repo_template/dbt"
ensure_dir "$MODULE/learning-materials/12_airflow_dbt_spark_lakehouse_architecture/airflow_lakehouse_repo_template/dbt/models"
ensure_dir "$MODULE/learning-materials/12_airflow_dbt_spark_lakehouse_architecture/airflow_lakehouse_repo_template/dbt/models/marts"
ensure_dir "$MODULE/learning-materials/12_airflow_dbt_spark_lakehouse_architecture/airflow_lakehouse_repo_template/dbt/models/staging"
ensure_dir "$MODULE/learning-materials/12_airflow_dbt_spark_lakehouse_architecture/airflow_lakehouse_repo_template/env"
ensure_dir "$MODULE/learning-materials/12_airflow_dbt_spark_lakehouse_architecture/airflow_lakehouse_repo_template/spark_jobs"
ensure_dir "$MODULE/learning-materials/12_airflow_dbt_spark_lakehouse_architecture/airflow_lakehouse_repo_template/tests"
ensure_dir "$MODULE/learning-materials/12_airflow_dbt_spark_lakehouse_architecture/airflow_platform_template_v2"
ensure_dir "$MODULE/learning-materials/12_airflow_dbt_spark_lakehouse_architecture/airflow_platform_template_v2/.github"
ensure_dir "$MODULE/learning-materials/12_airflow_dbt_spark_lakehouse_architecture/airflow_platform_template_v2/.github/workflows"
ensure_dir "$MODULE/learning-materials/12_airflow_dbt_spark_lakehouse_architecture/airflow_platform_template_v2/config"
ensure_dir "$MODULE/learning-materials/12_airflow_dbt_spark_lakehouse_architecture/airflow_platform_template_v2/dags"
ensure_dir "$MODULE/learning-materials/12_airflow_dbt_spark_lakehouse_architecture/airflow_platform_template_v2/dbt"
ensure_dir "$MODULE/learning-materials/12_airflow_dbt_spark_lakehouse_architecture/airflow_platform_template_v2/dbt/models"
ensure_dir "$MODULE/learning-materials/12_airflow_dbt_spark_lakehouse_architecture/airflow_platform_template_v2/dbt/models/marts"
ensure_dir "$MODULE/learning-materials/12_airflow_dbt_spark_lakehouse_architecture/airflow_platform_template_v2/dbt/models/staging"
ensure_dir "$MODULE/learning-materials/12_airflow_dbt_spark_lakehouse_architecture/airflow_platform_template_v2/env"
ensure_dir "$MODULE/learning-materials/12_airflow_dbt_spark_lakehouse_architecture/airflow_platform_template_v2/spark_jobs"
ensure_dir "$MODULE/learning-materials/12_airflow_dbt_spark_lakehouse_architecture/airflow_platform_template_v2/tests"

ensure_dir "$MODULE/simple-tasks"
ensure_dir "$MODULE/simple-tasks/01_first_dag"
ensure_dir "$MODULE/simple-tasks/02_task_dependencies"
ensure_dir "$MODULE/simple-tasks/03_scheduling_and_retries"
ensure_dir "$MODULE/simple-tasks/04_python_operator_pipeline"
ensure_dir "$MODULE/simple-tasks/05_airflow_with_external_jobs"
ensure_dir "$MODULE/simple-tasks/06_basic_monitoring"

ensure_dir "$MODULE/pet-projects"
ensure_dir "$MODULE/pet-projects/01_batch_pipeline_orchestration"
ensure_dir "$MODULE/pet-projects/01_batch_pipeline_orchestration/config"
ensure_dir "$MODULE/pet-projects/01_batch_pipeline_orchestration/data"
ensure_dir "$MODULE/pet-projects/01_batch_pipeline_orchestration/docker"
ensure_dir "$MODULE/pet-projects/01_batch_pipeline_orchestration/src"
ensure_dir "$MODULE/pet-projects/01_batch_pipeline_orchestration/tests"
ensure_dir "$MODULE/pet-projects/02_api_to_lakehouse_orchestration"
ensure_dir "$MODULE/pet-projects/02_api_to_lakehouse_orchestration/config"
ensure_dir "$MODULE/pet-projects/02_api_to_lakehouse_orchestration/data"
ensure_dir "$MODULE/pet-projects/02_api_to_lakehouse_orchestration/docker"
ensure_dir "$MODULE/pet-projects/02_api_to_lakehouse_orchestration/src"
ensure_dir "$MODULE/pet-projects/02_api_to_lakehouse_orchestration/tests"
ensure_dir "$MODULE/pet-projects/03_multi_step_data_workflow"
ensure_dir "$MODULE/pet-projects/03_multi_step_data_workflow/config"
ensure_dir "$MODULE/pet-projects/03_multi_step_data_workflow/data"
ensure_dir "$MODULE/pet-projects/03_multi_step_data_workflow/docker"
ensure_dir "$MODULE/pet-projects/03_multi_step_data_workflow/src"
ensure_dir "$MODULE/pet-projects/03_multi_step_data_workflow/tests"
ensure_dir "$MODULE/pet-projects/04_production_style_airflow_project"
ensure_dir "$MODULE/pet-projects/04_production_style_airflow_project/config"
ensure_dir "$MODULE/pet-projects/04_production_style_airflow_project/data"
ensure_dir "$MODULE/pet-projects/04_production_style_airflow_project/docker"
ensure_dir "$MODULE/pet-projects/04_production_style_airflow_project/src"
ensure_dir "$MODULE/pet-projects/04_production_style_airflow_project/tests"
ensure_dir "$MODULE/pet-projects/reference_example_api_to_lakehouse_orchestration"
ensure_dir "$MODULE/pet-projects/reference_example_api_to_lakehouse_orchestration/config"
ensure_dir "$MODULE/pet-projects/reference_example_api_to_lakehouse_orchestration/data"
ensure_dir "$MODULE/pet-projects/reference_example_api_to_lakehouse_orchestration/docker"
ensure_dir "$MODULE/pet-projects/reference_example_api_to_lakehouse_orchestration/src"
ensure_dir "$MODULE/pet-projects/reference_example_api_to_lakehouse_orchestration/src/dags"
ensure_dir "$MODULE/pet-projects/reference_example_api_to_lakehouse_orchestration/src/helpers"
ensure_dir "$MODULE/pet-projects/reference_example_api_to_lakehouse_orchestration/tests"
ensure_dir "$MODULE/pet-projects/reference_example_production_style_airflow_project"
ensure_dir "$MODULE/pet-projects/reference_example_production_style_airflow_project/config"
ensure_dir "$MODULE/pet-projects/reference_example_production_style_airflow_project/data"
ensure_dir "$MODULE/pet-projects/reference_example_production_style_airflow_project/docker"
ensure_dir "$MODULE/pet-projects/reference_example_production_style_airflow_project/src"
ensure_dir "$MODULE/pet-projects/reference_example_production_style_airflow_project/src/dags"
ensure_dir "$MODULE/pet-projects/reference_example_production_style_airflow_project/src/helpers"
ensure_dir "$MODULE/pet-projects/reference_example_production_style_airflow_project/tests"

log "Adding .gitkeep files where useful..."

ensure_gitkeep "$MODULE/learning-materials"
ensure_gitkeep "$MODULE/learning-materials/02_airflow_installation_and_deployment/dags"
ensure_gitkeep "$MODULE/learning-materials/12_airflow_dbt_spark_lakehouse_architecture/airflow_lakehouse_repo_template/config"
ensure_gitkeep "$MODULE/learning-materials/12_airflow_dbt_spark_lakehouse_architecture/airflow_lakehouse_repo_template/dags"
ensure_gitkeep "$MODULE/learning-materials/12_airflow_dbt_spark_lakehouse_architecture/airflow_lakehouse_repo_template/dbt/models/marts"
ensure_gitkeep "$MODULE/learning-materials/12_airflow_dbt_spark_lakehouse_architecture/airflow_lakehouse_repo_template/dbt/models/staging"
ensure_gitkeep "$MODULE/learning-materials/12_airflow_dbt_spark_lakehouse_architecture/airflow_lakehouse_repo_template/env"
ensure_gitkeep "$MODULE/learning-materials/12_airflow_dbt_spark_lakehouse_architecture/airflow_lakehouse_repo_template/spark_jobs"
ensure_gitkeep "$MODULE/learning-materials/12_airflow_dbt_spark_lakehouse_architecture/airflow_lakehouse_repo_template/tests"
ensure_gitkeep "$MODULE/learning-materials/12_airflow_dbt_spark_lakehouse_architecture/airflow_platform_template_v2/.github/workflows"
ensure_gitkeep "$MODULE/learning-materials/12_airflow_dbt_spark_lakehouse_architecture/airflow_platform_template_v2/config"
ensure_gitkeep "$MODULE/learning-materials/12_airflow_dbt_spark_lakehouse_architecture/airflow_platform_template_v2/dags"
ensure_gitkeep "$MODULE/learning-materials/12_airflow_dbt_spark_lakehouse_architecture/airflow_platform_template_v2/dbt/models/marts"
ensure_gitkeep "$MODULE/learning-materials/12_airflow_dbt_spark_lakehouse_architecture/airflow_platform_template_v2/dbt/models/staging"
ensure_gitkeep "$MODULE/learning-materials/12_airflow_dbt_spark_lakehouse_architecture/airflow_platform_template_v2/env"
ensure_gitkeep "$MODULE/learning-materials/12_airflow_dbt_spark_lakehouse_architecture/airflow_platform_template_v2/spark_jobs"
ensure_gitkeep "$MODULE/learning-materials/12_airflow_dbt_spark_lakehouse_architecture/airflow_platform_template_v2/tests"

ensure_gitkeep "$MODULE/simple-tasks/01_first_dag"
ensure_gitkeep "$MODULE/simple-tasks/02_task_dependencies"
ensure_gitkeep "$MODULE/simple-tasks/03_scheduling_and_retries"
ensure_gitkeep "$MODULE/simple-tasks/04_python_operator_pipeline"
ensure_gitkeep "$MODULE/simple-tasks/05_airflow_with_external_jobs"
ensure_gitkeep "$MODULE/simple-tasks/06_basic_monitoring"

ensure_gitkeep "$MODULE/pet-projects/01_batch_pipeline_orchestration/config"
ensure_gitkeep "$MODULE/pet-projects/01_batch_pipeline_orchestration/data"
ensure_gitkeep "$MODULE/pet-projects/01_batch_pipeline_orchestration/docker"
ensure_gitkeep "$MODULE/pet-projects/01_batch_pipeline_orchestration/src"
ensure_gitkeep "$MODULE/pet-projects/01_batch_pipeline_orchestration/tests"
ensure_gitkeep "$MODULE/pet-projects/02_api_to_lakehouse_orchestration/config"
ensure_gitkeep "$MODULE/pet-projects/02_api_to_lakehouse_orchestration/data"
ensure_gitkeep "$MODULE/pet-projects/02_api_to_lakehouse_orchestration/docker"
ensure_gitkeep "$MODULE/pet-projects/02_api_to_lakehouse_orchestration/src"
ensure_gitkeep "$MODULE/pet-projects/02_api_to_lakehouse_orchestration/tests"
ensure_gitkeep "$MODULE/pet-projects/03_multi_step_data_workflow/config"
ensure_gitkeep "$MODULE/pet-projects/03_multi_step_data_workflow/data"
ensure_gitkeep "$MODULE/pet-projects/03_multi_step_data_workflow/docker"
ensure_gitkeep "$MODULE/pet-projects/03_multi_step_data_workflow/src"
ensure_gitkeep "$MODULE/pet-projects/03_multi_step_data_workflow/tests"
ensure_gitkeep "$MODULE/pet-projects/04_production_style_airflow_project/config"
ensure_gitkeep "$MODULE/pet-projects/04_production_style_airflow_project/data"
ensure_gitkeep "$MODULE/pet-projects/04_production_style_airflow_project/docker"
ensure_gitkeep "$MODULE/pet-projects/04_production_style_airflow_project/src"
ensure_gitkeep "$MODULE/pet-projects/04_production_style_airflow_project/tests"
ensure_gitkeep "$MODULE/pet-projects/reference_example_api_to_lakehouse_orchestration/config"
ensure_gitkeep "$MODULE/pet-projects/reference_example_api_to_lakehouse_orchestration/data"
ensure_gitkeep "$MODULE/pet-projects/reference_example_api_to_lakehouse_orchestration/docker"
ensure_gitkeep "$MODULE/pet-projects/reference_example_api_to_lakehouse_orchestration/src/dags"
ensure_gitkeep "$MODULE/pet-projects/reference_example_api_to_lakehouse_orchestration/src/helpers"
ensure_gitkeep "$MODULE/pet-projects/reference_example_api_to_lakehouse_orchestration/tests"
ensure_gitkeep "$MODULE/pet-projects/reference_example_production_style_airflow_project/config"
ensure_gitkeep "$MODULE/pet-projects/reference_example_production_style_airflow_project/data"
ensure_gitkeep "$MODULE/pet-projects/reference_example_production_style_airflow_project/docker"
ensure_gitkeep "$MODULE/pet-projects/reference_example_production_style_airflow_project/src/dags"
ensure_gitkeep "$MODULE/pet-projects/reference_example_production_style_airflow_project/src/helpers"
ensure_gitkeep "$MODULE/pet-projects/reference_example_production_style_airflow_project/tests"

log "11-airflow structure initialized."