#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

source "$SCRIPT_DIR/../../../lib/common.sh"
source "$SCRIPT_DIR/../../../lib/fs.sh"
source "$SCRIPT_DIR/../../../lib/section.sh"

SCRIPT_NAME="03-docker-init"

REPO_ROOT="$(get_repo_root "$SCRIPT_DIR")"
MODULE="$(get_module_root "$REPO_ROOT" "03-docker")"

log "Creating 03-docker structure..."

ensure_dir "$MODULE"

ensure_dir "$MODULE/learning-materials"

ensure_dir "$MODULE/simple-tasks"
ensure_dir "$MODULE/simple-tasks/01_run_containers"
ensure_dir "$MODULE/simple-tasks/02_images_and_registry"
ensure_dir "$MODULE/simple-tasks/03_ports_volumes_and_networks"
ensure_dir "$MODULE/simple-tasks/04_dockerfile_basics"
ensure_dir "$MODULE/simple-tasks/05_docker_compose_basics"
ensure_dir "$MODULE/simple-tasks/06_debugging_and_inspection"
ensure_dir "$MODULE/simple-tasks/07_data_engineering_local_stacks"

ensure_dir "$MODULE/pet-projects"
ensure_dir "$MODULE/pet-projects/01_python_batch_job_in_docker"
ensure_dir "$MODULE/pet-projects/01_python_batch_job_in_docker/config"
ensure_dir "$MODULE/pet-projects/01_python_batch_job_in_docker/data"
ensure_dir "$MODULE/pet-projects/01_python_batch_job_in_docker/data/input"
ensure_dir "$MODULE/pet-projects/01_python_batch_job_in_docker/data/output"
ensure_dir "$MODULE/pet-projects/01_python_batch_job_in_docker/docker"
ensure_dir "$MODULE/pet-projects/01_python_batch_job_in_docker/src"
ensure_dir "$MODULE/pet-projects/01_python_batch_job_in_docker/tests"
ensure_dir "$MODULE/pet-projects/02_etl_with_postgres_compose"
ensure_dir "$MODULE/pet-projects/02_etl_with_postgres_compose/config"
ensure_dir "$MODULE/pet-projects/02_etl_with_postgres_compose/data"
ensure_dir "$MODULE/pet-projects/02_etl_with_postgres_compose/data/input"
ensure_dir "$MODULE/pet-projects/02_etl_with_postgres_compose/docker"
ensure_dir "$MODULE/pet-projects/02_etl_with_postgres_compose/src"
ensure_dir "$MODULE/pet-projects/02_etl_with_postgres_compose/tests"
ensure_dir "$MODULE/pet-projects/03_api_worker_and_db_stack"
ensure_dir "$MODULE/pet-projects/03_api_worker_and_db_stack/config"
ensure_dir "$MODULE/pet-projects/03_api_worker_and_db_stack/data"
ensure_dir "$MODULE/pet-projects/03_api_worker_and_db_stack/data/requests"
ensure_dir "$MODULE/pet-projects/03_api_worker_and_db_stack/docker"
ensure_dir "$MODULE/pet-projects/03_api_worker_and_db_stack/src"
ensure_dir "$MODULE/pet-projects/03_api_worker_and_db_stack/tests"
ensure_dir "$MODULE/pet-projects/04_local_data_platform_foundation"
ensure_dir "$MODULE/pet-projects/04_local_data_platform_foundation/config"
ensure_dir "$MODULE/pet-projects/04_local_data_platform_foundation/data"
ensure_dir "$MODULE/pet-projects/04_local_data_platform_foundation/data/input"
ensure_dir "$MODULE/pet-projects/04_local_data_platform_foundation/docker"
ensure_dir "$MODULE/pet-projects/04_local_data_platform_foundation/src"
ensure_dir "$MODULE/pet-projects/04_local_data_platform_foundation/tests"
ensure_dir "$MODULE/pet-projects/reference_example_python_batch_job_in_docker"
ensure_dir "$MODULE/pet-projects/reference_example_etl_with_postgres_compose"
ensure_dir "$MODULE/pet-projects/reference_example_api_worker_and_db_stack"
ensure_dir "$MODULE/pet-projects/reference_example_local_data_platform_foundation"

log "Adding .gitkeep files where useful..."

ensure_gitkeep "$MODULE/learning-materials"

ensure_gitkeep "$MODULE/simple-tasks/01_run_containers"
ensure_gitkeep "$MODULE/simple-tasks/02_images_and_registry"
ensure_gitkeep "$MODULE/simple-tasks/03_ports_volumes_and_networks"
ensure_gitkeep "$MODULE/simple-tasks/04_dockerfile_basics"
ensure_gitkeep "$MODULE/simple-tasks/05_docker_compose_basics"
ensure_gitkeep "$MODULE/simple-tasks/06_debugging_and_inspection"
ensure_gitkeep "$MODULE/simple-tasks/07_data_engineering_local_stacks"

ensure_gitkeep "$MODULE/pet-projects/01_python_batch_job_in_docker/config"
ensure_gitkeep "$MODULE/pet-projects/01_python_batch_job_in_docker/data/input"
ensure_gitkeep "$MODULE/pet-projects/01_python_batch_job_in_docker/data/output"
ensure_gitkeep "$MODULE/pet-projects/01_python_batch_job_in_docker/docker"
ensure_gitkeep "$MODULE/pet-projects/01_python_batch_job_in_docker/src"
ensure_gitkeep "$MODULE/pet-projects/01_python_batch_job_in_docker/tests"
ensure_gitkeep "$MODULE/pet-projects/02_etl_with_postgres_compose/config"
ensure_gitkeep "$MODULE/pet-projects/02_etl_with_postgres_compose/data/input"
ensure_gitkeep "$MODULE/pet-projects/02_etl_with_postgres_compose/docker"
ensure_gitkeep "$MODULE/pet-projects/02_etl_with_postgres_compose/src"
ensure_gitkeep "$MODULE/pet-projects/02_etl_with_postgres_compose/tests"
ensure_gitkeep "$MODULE/pet-projects/03_api_worker_and_db_stack/config"
ensure_gitkeep "$MODULE/pet-projects/03_api_worker_and_db_stack/data/requests"
ensure_gitkeep "$MODULE/pet-projects/03_api_worker_and_db_stack/docker"
ensure_gitkeep "$MODULE/pet-projects/03_api_worker_and_db_stack/src"
ensure_gitkeep "$MODULE/pet-projects/03_api_worker_and_db_stack/tests"
ensure_gitkeep "$MODULE/pet-projects/04_local_data_platform_foundation/config"
ensure_gitkeep "$MODULE/pet-projects/04_local_data_platform_foundation/data/input"
ensure_gitkeep "$MODULE/pet-projects/04_local_data_platform_foundation/docker"
ensure_gitkeep "$MODULE/pet-projects/04_local_data_platform_foundation/src"
ensure_gitkeep "$MODULE/pet-projects/04_local_data_platform_foundation/tests"
ensure_gitkeep "$MODULE/pet-projects/reference_example_python_batch_job_in_docker"
ensure_gitkeep "$MODULE/pet-projects/reference_example_etl_with_postgres_compose"
ensure_gitkeep "$MODULE/pet-projects/reference_example_api_worker_and_db_stack"
ensure_gitkeep "$MODULE/pet-projects/reference_example_local_data_platform_foundation"

log "03-docker structure initialized."