version: "3.8"

x-airflow-common:
  &airflow-common
  image: apache/airflow:2.9.3
  env_file:
    - .env
  environment:
    AIRFLOW__CORE__EXECUTOR: ${AIRFLOW__CORE__EXECUTOR}
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
    AIRFLOW__CELERY__BROKER_URL: ${AIRFLOW__CELERY__BROKER_URL}
    AIRFLOW__CELERY__RESULT_BACKEND: ${AIRFLOW__CELERY__RESULT_BACKEND}
    AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
    AIRFLOW__CORE__LOAD_EXAMPLES: ${AIRFLOW__CORE__LOAD_EXAMPLES}
    AIRFLOW__API__AUTH_BACKENDS: ${AIRFLOW__API__AUTH_BACKENDS}
    AIRFLOW_UID: 50000
    S3_RAW_BUCKET: ${S3_RAW_BUCKET}
    S3_CURATED_BUCKET: ${S3_CURATED_BUCKET}
    DBT_TARGET: ${DBT_TARGET}
    DBT_PROJECT_DIR: ${DBT_PROJECT_DIR}
    DBT_PROFILES_DIR: ${DBT_PROFILES_DIR}
    API_BASE_URL: ${API_BASE_URL}
    ALERT_SLACK_CHANNEL: ${ALERT_SLACK_CHANNEL}
  volumes:
    - ./dags:/opt/airflow/dags
    - ./config:/opt/airflow/config
    - ./spark_jobs:/opt/airflow/spark_jobs
    - ./dbt:/opt/airflow/dbt
    - ./tests:/opt/airflow/tests
    - ./logs:/opt/airflow/logs
  depends_on:
    postgres:
      condition: service_healthy
    redis:
      condition: service_started

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  redis:
    image: redis:7

  airflow-init:
    <<: *airflow-common
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create
      --username admin
      --firstname Admin
      --lastname User
      --role Admin
      --email admin@example.com
      --password admin
      "
    restart: "no"

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler

  airflow-worker:
    <<: *airflow-common
    command: celery worker

volumes:
  postgres-db-volume:
