#!/usr/bin/env bash

set -euo pipefail

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 <section-name>"
  echo "Supported: ai-learning | docs | real-projects | shared"
  exit 1
fi

SECTION="$1"

case "$SECTION" in
  ai-learning|docs|real-projects|shared)
    ;;
  *)
    echo "Unsupported section: $SECTION"
    exit 1
    ;;
esac

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

SCRIPT_NAME="create-section"

source "$REPO_ROOT/scripts/lib/common.sh"
source "$REPO_ROOT/scripts/lib/fs.sh"

SECTION_SCRIPT_DIR="$REPO_ROOT/scripts/sections/$SECTION"

log "Creating script scaffold for section: $SECTION"

ensure_dir "$SECTION_SCRIPT_DIR"
ensure_file "$SECTION_SCRIPT_DIR/init.sh"
ensure_file "$SECTION_SCRIPT_DIR/fill_readme.sh"
ensure_file "$SECTION_SCRIPT_DIR/bootstrap.sh"

write_file_safe "$SECTION_SCRIPT_DIR/init.sh" <<'EOF'
#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

source "$SCRIPT_DIR/../../lib/common.sh"
source "$SCRIPT_DIR/../../lib/fs.sh"
source "$SCRIPT_DIR/../../lib/section.sh"

SCRIPT_NAME="__SECTION__-init"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
SECTION_ROOT="$REPO_ROOT/__SECTION__"

log "Creating __SECTION__ structure..."

ensure_dir "$SECTION_ROOT"
ensure_gitkeep "$SECTION_ROOT"

log "__SECTION__ structure initialized."
EOF

write_file_safe "$SECTION_SCRIPT_DIR/fill_readme.sh" <<'EOF'
#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

source "$SCRIPT_DIR/../../lib/common.sh"
source "$SCRIPT_DIR/../../lib/fs.sh"

SCRIPT_NAME="__SECTION__-fill-readme"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
SECTION_ROOT="$REPO_ROOT/__SECTION__"

log "Creating __SECTION__ README..."

write_file_safe "$SECTION_ROOT/README.md" <<'DOC'
# __SECTION__

Section placeholder generated by scripts/create_section.sh.
DOC

log "__SECTION__ README created."
EOF

write_file_safe "$SECTION_SCRIPT_DIR/bootstrap.sh" <<'EOF'
#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

source "$SCRIPT_DIR/../../lib/common.sh"

SCRIPT_NAME="__SECTION__-bootstrap"

log "Starting __SECTION__ bootstrap..."

bash "$SCRIPT_DIR/init.sh"
bash "$SCRIPT_DIR/fill_readme.sh"

log "__SECTION__ bootstrap finished successfully."
EOF

for script_file in \
  "$SECTION_SCRIPT_DIR/init.sh" \
  "$SECTION_SCRIPT_DIR/fill_readme.sh" \
  "$SECTION_SCRIPT_DIR/bootstrap.sh"
do
  perl -0pi -e 's/__SECTION__/'"$SECTION"'/g' "$script_file"
done

chmod +x "$SECTION_SCRIPT_DIR/init.sh"
chmod +x "$SECTION_SCRIPT_DIR/fill_readme.sh"
chmod +x "$SECTION_SCRIPT_DIR/bootstrap.sh"

log "Section script scaffold created: scripts/sections/$SECTION"
log "Run with: ./scripts/bootstrap_section.sh $SECTION"