#!/usr/bin/env bash

set -euo pipefail

MODULE="02-sql/simple-tasks"

write_file_safe() {
  local file="$1"
  local tmp

  mkdir -p "$(dirname "$file")"

  if [ -s "$file" ]; then
    echo "[SKIP] $file already has content"
    return 0
  fi

  tmp="$(mktemp)"
  cat > "$tmp"
  mv "$tmp" "$file"

  echo "[WRITE] $file"
}

echo "Filling SQL simple tasks..."

write_file_safe "$MODULE/01_analytics_queries/README.md" <<'EOF'
# 01 Analytics Queries

## Overview

These tasks focus on practical SQL analytics patterns used in real data engineering and analytics work.

Suggested dataset tables:

- users
- orders
- order_items
- products
- payments
- events

---

## Task 1 — Revenue Per Customer

### Goal

Calculate total revenue generated by each customer.

### Input

Table:

- orders

Relevant columns:

- order_id
- user_id
- status
- amount
- order_date

### Requirements

- include only completed or paid orders
- group by user_id
- calculate total revenue
- sort by revenue descending

### Expected Output

Columns:

- user_id
- total_revenue

### Extra Challenge

Add:

- order_count
- average_order_value
- first_order_date
- last_order_date

---

## Task 2 — Top 10 Products by Revenue

### Goal

Find the top 10 products that generated the highest revenue.

### Input

Tables:

- order_items
- products

Relevant columns:

- order_items.product_id
- order_items.quantity
- order_items.item_price
- products.product_name

### Requirements

- calculate revenue as quantity * item_price
- aggregate by product_id
- optionally join products for readable names
- sort descending
- return top 10

### Expected Output

Columns:

- product_id
- product_name
- total_revenue

### Extra Challenge

Also return:

- total_quantity_sold
- number_of_orders_containing_product

---

## Task 3 — Daily Revenue Trend

### Goal

Build a daily revenue time series.

### Input

Table:

- orders

Relevant columns:

- order_date
- status
- amount

### Requirements

- use only paid/completed orders
- aggregate by day
- sort by day ascending

### Expected Output

Columns:

- revenue_date
- daily_revenue

### Extra Challenge

Add a 7-day moving average column.

---

## Task 4 — Customer Lifetime Value

### Goal

Calculate lifetime value for each customer.

### Input

Table:

- orders

Relevant columns:

- user_id
- order_id
- amount
- status
- order_date

### Requirements

- include only paid/completed orders
- aggregate by customer
- calculate total revenue across all valid orders

### Expected Output

Columns:

- user_id
- lifetime_value

### Extra Challenge

Add:

- total_orders
- average_order_value
- active_days_between_first_and_last_order

---

## Task 5 — Top Customers Per Country

### Goal

Find the top 3 customers by revenue inside each country.

### Input

Tables:

- users
- orders

Relevant columns:

- users.user_id
- users.country
- orders.user_id
- orders.amount
- orders.status

### Requirements

- join users with orders
- include only paid/completed orders
- aggregate revenue per user per country
- use a window function to rank inside each country
- return only top 3

### Expected Output

Columns:

- country
- user_id
- total_revenue
- rank_in_country

### Extra Challenge

Use both:

- ROW_NUMBER
- RANK

and explain the difference.

---

## Task 6 — Average Order Value by Month

### Goal

Calculate average order value for each month.

### Input

Table:

- orders

Relevant columns:

- order_date
- amount
- status

### Requirements

- use only valid orders
- truncate date to month
- calculate average amount
- sort chronologically

### Expected Output

Columns:

- order_month
- average_order_value

### Extra Challenge

Add monthly order count and monthly revenue.

---

## Task 7 — Paid vs Cancelled Order Breakdown

### Goal

Compare order counts and revenue across statuses.

### Input

Table:

- orders

Relevant columns:

- status
- amount
- order_id

### Requirements

- aggregate by status
- calculate order count
- calculate total amount

### Expected Output

Columns:

- status
- order_count
- total_amount

### Extra Challenge

Add percentage share of each status relative to total orders.

---

## Task 8 — Product Category Contribution

### Goal

Calculate how much each product category contributes to total revenue.

### Input

Tables:

- order_items
- products

Relevant columns:

- order_items.product_id
- order_items.quantity
- order_items.item_price
- products.category_id
- products.category_name

### Requirements

- calculate revenue at item level
- aggregate by category
- calculate percentage of total revenue
- sort descending

### Expected Output

Columns:

- category_id
- category_name
- category_revenue
- revenue_share_pct

### Extra Challenge

Return both category rank and cumulative revenue share.

EOF

write_file_safe "$MODULE/02_window_queries/README.md" <<'EOF'
# 02 Window Queries

## Overview

These tasks focus on window-function-based patterns frequently used in analytics engineering and data platform work.

Suggested dataset tables:

- orders
- events
- customers
- daily_metrics

---

## Task 1 — Rank Orders Per User

### Goal

Assign a sequential order number to each user's orders.

### Input

Table:

- orders

Relevant columns:

- user_id
- order_id
- order_date

### Requirements

- partition by user_id
- order by order_date
- assign row number

### Expected Output

Columns:

- user_id
- order_id
- order_date
- order_number

### Extra Challenge

Also calculate:

- reverse order number (latest = 1)

---

## Task 2 — Running Customer Revenue

### Goal

Calculate cumulative revenue per customer over time.

### Input

Table:

- orders

Relevant columns:

- user_id
- order_date
- amount
- status

### Requirements

- include only paid/completed orders
- partition by user_id
- order by order_date
- calculate running sum

### Expected Output

Columns:

- user_id
- order_date
- amount
- running_customer_revenue

### Extra Challenge

Return running order count together with running revenue.

---

## Task 3 — Global Running Revenue

### Goal

Calculate cumulative revenue across the whole business timeline.

### Input

Table:

- orders

Relevant columns:

- order_date
- amount
- status

### Requirements

- aggregate by day first or document why you do not
- order by date
- calculate cumulative revenue

### Expected Output

Columns:

- revenue_date
- daily_revenue
- running_revenue

### Extra Challenge

Add cumulative average daily revenue.

---

## Task 4 — 7-Day Moving Average

### Goal

Smooth daily revenue using a 7-day moving average.

### Input

Table:

- daily_revenue or derived daily revenue dataset

Relevant columns:

- revenue_date
- daily_revenue

### Requirements

- order by date
- calculate 7-day moving average
- use a proper window frame

### Expected Output

Columns:

- revenue_date
- daily_revenue
- moving_avg_7d

### Extra Challenge

Also calculate 3-day and 30-day moving averages.

---

## Task 5 — Previous and Next Order

### Goal

Show previous and next order timestamps for each customer order.

### Input

Table:

- orders

Relevant columns:

- user_id
- order_id
- order_date

### Requirements

- use LAG
- use LEAD
- partition by user_id
- order by order_date

### Expected Output

Columns:

- user_id
- order_id
- order_date
- previous_order_date
- next_order_date

### Extra Challenge

Also calculate days_since_previous_order.

---

## Task 6 — Latest Record Per Entity

### Goal

Return only the latest record per entity from an update stream.

### Input

Table:

- customer_updates or orders_raw

Relevant columns:

- entity_id
- updated_at
- payload_version or event_id

### Requirements

- partition by entity_id
- order by updated_at descending
- keep only latest row

### Expected Output

Columns:

- entity_id
- updated_at
- latest_payload_columns

### Extra Challenge

Make the ordering deterministic when timestamps are equal.

---

## Task 7 — Sessionization Flag

### Goal

Mark whether an event starts a new session.

### Input

Table:

- events

Relevant columns:

- user_id
- event_time
- event_name

### Requirements

- partition by user_id
- order by event_time
- compare current event_time with previous event_time
- define a session timeout, for example 30 minutes

### Expected Output

Columns:

- user_id
- event_time
- previous_event_time
- new_session_flag

### Extra Challenge

Create a session_id using cumulative sum over new_session_flag.

---

## Task 8 — Top N Inside Partition

### Goal

Return top 5 products per category by revenue.

### Input

Tables:

- order_items
- products

Relevant columns:

- product_id
- category_id
- quantity
- item_price

### Requirements

- aggregate revenue per product
- partition by category
- rank by revenue descending
- keep only top 5

### Expected Output

Columns:

- category_id
- product_id
- total_revenue
- rank_in_category

### Extra Challenge

Compare ROW_NUMBER vs RANK vs DENSE_RANK on the same dataset.

EOF

write_file_safe "$MODULE/03_document_queries/README.md" <<'EOF'
# 03 Document Queries

## Overview

These tasks focus on document-oriented queries, mainly with MongoDB-style patterns.

Suggested collections:

- orders
- users
- events
- sessions

Example document:

```json
{
  "order_id": 101,
  "customer_id": 10,
  "status": "paid",
  "amount": 250,
  "customer": {
    "country": "PL"
  },
  "items": [
    {"sku": "A1", "qty": 2, "price": 100},
    {"sku": "B2", "qty": 1, "price": 50}
  ],
  "tags": ["priority", "electronics"]
}
```

---

## Task 1 — Read All Documents

### Goal

Return all documents from the orders collection.

### Input

Collection:

- orders

### Requirements

- read all documents
- do not apply filters

### Expected Output

Full set of order documents.

### Extra Challenge

Return only the first 10 documents.

---

## Task 2 — Equality Filter

### Goal

Return all paid orders.

### Input

Collection:

- orders

Relevant fields:

- status

### Requirements

- filter on status = paid

### Expected Output

Only documents where status is paid.

### Extra Challenge

Also return paid orders for one specific customer_id.

---

## Task 3 — Range Filter

### Goal

Return all orders with amount greater than 100.

### Input

Collection:

- orders

Relevant fields:

- amount

### Requirements

- apply numeric range filter

### Expected Output

Documents where amount > 100.

### Extra Challenge

Filter amount between 100 and 500.

---

## Task 4 — Combined Filter

### Goal

Return all paid orders with amount between 100 and 500.

### Input

Collection:

- orders

Relevant fields:

- status
- amount

### Requirements

- combine equality and range filter

### Expected Output

Documents that satisfy both conditions.

### Extra Challenge

Add customer.country = "PL" to the filter.

---

## Task 5 — Projection

### Goal

Return only selected fields from documents.

### Input

Collection:

- orders

Relevant fields:

- order_id
- customer_id
- amount
- status

### Requirements

- exclude _id
- include only required fields

### Expected Output

Documents containing only selected fields.

### Extra Challenge

Add a computed field later through aggregation.

---

## Task 6 — Sorting

### Goal

Return orders sorted by amount descending.

### Input

Collection:

- orders

Relevant fields:

- amount

### Requirements

- sort descending

### Expected Output

Documents ordered by amount from highest to lowest.

### Extra Challenge

Sort by status ascending and amount descending.

---

## Task 7 — Pagination

### Goal

Return page 3 with page size 10.

### Input

Collection:

- orders

Relevant fields:

- order_id or another sorting key

### Requirements

- sort deterministically
- skip first 20
- limit 10

### Expected Output

10 documents representing page 3.

### Extra Challenge

Explain why skip-based pagination may become expensive on large collections.

---

## Task 8 — Count Paid Orders

### Goal

Count the number of paid orders.

### Input

Collection:

- orders

Relevant fields:

- status

### Requirements

- count only paid documents

### Expected Output

Single numeric count.

### Extra Challenge

Return counts by status using aggregation.

---

## Task 9 — Distinct Statuses

### Goal

Return all distinct order statuses.

### Input

Collection:

- orders

Relevant fields:

- status

### Requirements

- return unique values only

### Expected Output

Distinct list of statuses.

### Extra Challenge

Return distinct countries from nested customer.country.

---

## Task 10 — Nested Field Query

### Goal

Return all orders where customer.country = "PL".

### Input

Collection:

- orders

Relevant fields:

- customer.country

### Requirements

- query nested field

### Expected Output

Documents whose nested customer.country equals PL.

### Extra Challenge

Add status = paid to the same query.

---

## Task 11 — Array Membership

### Goal

Return all orders tagged as priority.

### Input

Collection:

- orders

Relevant fields:

- tags

### Requirements

- match documents containing one array value

### Expected Output

Documents where tags contains "priority".

### Extra Challenge

Match documents containing both "priority" and "electronics".

---

## Task 12 — elemMatch

### Goal

Find orders where one embedded item has sku = A1 and qty >= 2.

### Input

Collection:

- orders

Relevant fields:

- items.sku
- items.qty

### Requirements

- use elemMatch
- ensure both conditions match the same array element

### Expected Output

Orders containing at least one matching item object.

### Extra Challenge

Also filter orders with amount > 100.

---

## Task 13 — Aggregation by Status

### Goal

Group orders by status and calculate count and total amount.

### Input

Collection:

- orders

Relevant fields:

- status
- amount

### Requirements

- use aggregation pipeline
- group by status
- count documents
- sum amount

### Expected Output

Columns / fields:

- status
- order_count
- total_amount

### Extra Challenge

Sort aggregated result by total_amount descending.

---

## Task 14 — Aggregation by Customer

### Goal

Group paid orders by customer_id and calculate total amount.

### Input

Collection:

- orders

Relevant fields:

- customer_id
- status
- amount

### Requirements

- filter to paid orders first
- group by customer_id
- calculate total amount

### Expected Output

Documents showing customer-level paid revenue.

### Extra Challenge

Return top 10 customers by total_amount.

EOF

write_file_safe "$MODULE/04_nosql_modeling/README.md" <<'EOF'
# 04 NoSQL Modeling

## Overview

These tasks focus on schema design for NoSQL systems instead of direct relational translation.

Source relational entities:

- users
- orders
- order_items
- products
- events
- sessions

---

## Task 1 — SQL to MongoDB Order Model

### Goal

Convert relational order tables into a MongoDB-friendly document model.

### Input

Relational tables:

- orders
- order_items
- products

### Requirements

- decide what to embed
- decide what to reference
- explain document boundaries
- explain risks of document growth

### Expected Output

- proposed order document schema
- example document
- explanation of design choices

### Extra Challenge

Design both:
- embedded model
- hybrid embedded + referenced model

and compare them.

---

## Task 2 — SQL to DynamoDB Order Access Pattern Model

### Goal

Design a DynamoDB schema for customer order access patterns.

### Input

Business requirements:

- get all orders for customer
- get latest orders for customer
- get orders by product through GSI

### Requirements

- define PK
- define SK
- define at least one GSI
- explain access pattern mapping
- explain hot partition risks

### Expected Output

- table design
- example items
- example query patterns
- index strategy

### Extra Challenge

Design a sharded version for high-traffic customers.

---

## Task 3 — SQL to CosmosDB Order Model

### Goal

Design a CosmosDB order model and choose a partition key.

### Input

Relational domain:

- orders
- order_items
- customers

### Requirements

- define JSON document shape
- choose partition key
- explain why the partition key is good
- explain which queries are cheap and expensive

### Expected Output

- proposed schema
- example document
- partition key decision note
- trade-off explanation

### Extra Challenge

Compare:
- partition by customer_id
- partition by order_id

and explain which is better for common operational queries.

---

## Task 4 — Session Event Modeling Across Systems

### Goal

Model session or event data in multiple NoSQL systems.

### Input

Domain:

- users
- sessions
- events

### Requirements

- propose model for MongoDB
- propose model for DynamoDB
- propose model for CosmosDB
- explain differences in access path design

### Expected Output

- three model variants
- example documents/items
- query/access pattern explanation
- trade-off comparison

### Extra Challenge

Explain which model is best for:
- operational reads
- analytics export
- high write throughput

---

## Task 5 — Product Catalog with Flexible Attributes

### Goal

Model a flexible product catalog where products have different attribute sets.

### Input

Product examples:

- laptop with CPU/RAM/storage
- shoes with size/material/color
- book with author/language/pages

### Requirements

- propose SQL model
- propose MongoDB model
- propose CosmosDB model
- explain where flexible schema is useful

### Expected Output

- schemas for each system
- example records/documents
- strengths and weaknesses of each approach

### Extra Challenge

Add a search/filter requirement and explain which fields should be indexed.
EOF

echo "Simple tasks completed."