name: 'platform_demo'
version: '1.0.0'
config-version: 2

profile: 'platform_demo'

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  platform_demo:
    staging:
      +materialized: view
    marts:
      +materialized: table
